### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by tgabi333** [MetaMask/metamask-logo#13]
Chrome (65) always repaints the logo even if there is no mouse move which results at least 50% CPU usage all the time.

Same load for Chrome Extension.

**Comment by kumavis** [comment]
Curious, where are you using this?

**Comment by danfinlay** [comment]
Opened issue against MetaMask too here: https://github.com/MetaMask/metamask-extension/issues/3621

**Comment by danfinlay** [comment]
Fixed by #3621, published as `2.1.4`.
